### ISSUE TITLE
INTERNAL_PRIVILEGED lookupModes on jdk11-openj9

### ISSUE THREAD

**Issue by JaynLau** [toolfactory/jvm-driver#40]
When getting a MethodHandles.Lookup on  jdk11-openj9, `driver.getConsulter()` returns a lookup instance with INTERNAL_PRIVILEGED lookupModes, not -1.

**Comment by Roberto-Gentili** [comment]
Really very strange because the driver as you can see from these links is also tested for this version of JDK:
- [Adopt OpenJDK OpenJ9](https://github.com/toolfactory/jvm-driver/runs/5655556016?check_suite_focus=true)
- [Tests](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/BaseTest.java#L24)

Could you provide a link to download the JDK you are using?

**Comment by Roberto-Gentili** [comment]
Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?

**Comment by Roberto-Gentili** [comment]
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the version you are using does not support the value -1 as a lookup mode
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the version you are using does not support the value -1 as lookup mode.
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the version you are using does not support the value -1 as lookup mode.
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 11 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the version you are using does not support the TRUSTED mode (value -1) as lookup mode.
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 11 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the JDK version you are using does not support the TRUSTED mode (value -1) as lookup mode.
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 11 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Does in this mode MethodHandles.Lookup not working or unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by Roberto-Gentili** [comment]
If I remember correctly the JDK version you are using does not support the TRUSTED mode (value -1) as lookup mode.
As you can see in these links, the JVM Driver is tested also for the version you are using:
- [Adopt OpenJ9 11 tests](https://github.com/toolfactory/jvm-driver/runs/5659053555?check_suite_focus=true)
- [getConsulter method test code](https://github.com/toolfactory/jvm-driver/blob/a776a5e01b54c82e85babf79a0af0014f0b540ad/java/src/test/java/io/github/toolfactory/jvm/test/DefaultDriverTest.java#L30)

Is there any case where the MethodHandles.Lookup with this mode doesn't work or is unable to retrieve private members?
Is [**this**](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=openj9) the version are you using?

**Comment by JaynLau** [comment]
Yes, ibm-semeru-runtimes-11 is my working jdk now.

The default mode of openj9 11 (INTERNAL_PRIVILEGED) can not be used by LambdaMetafactory.
```
java.lang.invoke.LambdaConversionException: Invalid caller: test.beans.model.Entity
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:119)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:159)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:324)
	at io.chedu.util.Beans$Setters.createSetter(Beans.java:321)
	at io.chedu.util.Beans$Setters.lambda$get$2(Beans.java:338)
        ...
```
The follow solution combined with `Driver.setAccessible()` works fine on openj9 8, openj9 11, openj9 17, openj9 18 in my case.
```
public static Lookup lookup(Class<?> type) {
    return LOOKUP_FACTORY.apply(type);
}

private static final Constructor<MethodHandles.Lookup> LOOKUP_CONSTRUCTOR = getLookupConstructor();
private static Constructor<MethodHandles.Lookup> getLookupConstructor() {
    try {
        Constructor<MethodHandles.Lookup> c;
        if (JVM_VERSION >= 17) {
            c = MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, Class.class, int.class);
        } else {
            c = MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, int.class);
        }
        makeAccessible(c);
        return c;
    } catch (Exception e) {
        return Throwables.sneakyThrow(e);
    }
}

private static final Function<Class<?>, Lookup> LOOKUP_FACTORY = createLookupFactory();
private static Function<Class<?>, Lookup> createLookupFactory() {
    if (JVM_VERSION >= 17) {
        return (type) -> {
            try {
                return LOOKUP_CONSTRUCTOR.newInstance(
                        type,
                        null,
                        -1 // Lookup.TRUSTED
                );
            } catch (Exception e) {
                return Throwables.sneakyThrow(e);
            }
        };
    } else {
        return (type) -> {
            try {
                return LOOKUP_CONSTRUCTOR.newInstance(
                        type,
                        -1 // Lookup.TRUSTED
                );
            } catch (Exception e) {
                return Throwables.sneakyThrow(e);
            }
        };
    }
}
```

**Comment by Roberto-Gentili** [comment]
> Yes, ibm-semeru-runtimes-11 is my working jdk now.
> 
> The default mode of openj9 11 (INTERNAL_PRIVILEGED) can not be used by LambdaMetafactory.
> 
> ```
> java.lang.invoke.LambdaConversionException: Invalid caller: test.beans.model.Entity
> 	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:119)
> 	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:159)
> 	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:324)
> 	at io.chedu.util.Beans$Setters.createSetter(Beans.java:321)
> 	at io.chedu.util.Beans$Setters.lambda$get$2(Beans.java:338)
>         ...
> ```
> 
> The follow solution combined with `Driver.setAccessible()` works fine on openj9 8, openj9 11, openj9 17, openj9 18 in my case.
> 
> ```
> public static Lookup lookup(Class<?> type) {
>     return LOOKUP_FACTORY.apply(type);
> }
> 
> private static Constructor<MethodHandles.Lookup> getLookupConstructor() {
>     try {
>         Constructor<MethodHandles.Lookup> c;
>         if (JVM_VERSION >= 17) {
>             c = MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, Class.class, int.class);
>         } else {
>             c = MethodHandles.Lookup.class.getDeclaredConstructor(Class.class, int.class);
>         }
>         makeAccessible(c);
>         return c;
>     } catch (Exception e) {
>         return Throwables.sneakyThrow(e);
>     }
> }
> 
> private static final Function<Class<?>, Lookup> LOOKUP_FACTORY = createLookupFactory();
> private static Function<Class<?>, Lookup> createLookupFactory() {
>     Constructor<MethodHandles.Lookup> c = getLookupConstructor();
>     if (JVM_VERSION >= 17) {
>         return (type) -> {
>             try {
>                 return c.newInstance(
>                         type,
>                         null,
>                         -1 // Lookup.TRUSTED
>                 );
>             } catch (Exception e) {
>                 return Throwables.sneakyThrow(e);
>             }
>         };
>     } else {
>         return (type) -> {
>             try {
>                 return c.newInstance(
>                         type,
>                         -1 // Lookup.TRUSTED
>                 );
>             } catch (Exception e) {
>                 return Throwables.sneakyThrow(e);
>             }
>         };
>     }
> }
> ```

I tried to set the value -1 to the accessMode field of MethodHandles.Lookup on Semeru JDK but i get this error:

```
java.lang.IllegalArgumentException: java.lang.IllegalAccessException: Module 'org.burningwave.core' no access to: package 'org.burningwave.core.service' which is not exported by module 'org.burningwave.core'
	at java.base/java.lang.invoke.MethodHandles$Lookup.revealDirect(MethodHandles.java:1409)
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:133)
	at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:159)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:324)
```
... Unfortunately, as I said before, the Semeru JDK does not support TRUSTED mode

**Comment by Roberto-Gentili** [comment]
... I think on Semeru the Driver should use FULL_ACCESS_MASK mode

**Comment by Roberto-Gentili** [comment]
I just released version 9.0.0 which fixes this problem: could you download and try?

**Comment by JaynLau** [comment]
OK, it works fine now. Thanks.

**Comment by JaynLau** [comment]
By the way, is there any plan to support other archtecture or improve the performance?

I tested the property access performance with jmh on jdk17-hotspot before, jvm-driver or narcissus is too slow.

![image](https://user-images.githubusercontent.com/1670721/172523829-36d59ba7-2b50-4c7c-b1dd-f03202d94676.png)

**Comment by lukehutch** [comment]
@JaynLau re. other architectures: there's a feature request to add Aarch64 support to Narcissus (which could be used by JVM-Driver), but I don't have time to work on it (patches are welcome).

https://github.com/toolfactory/narcissus/issues/10

Narcissus is really not ever going to be fast, because it works through JNI, which is very slow.

There may be a possibility to use JVM-Driver or even Narcissus to create a `MethodHandle` to call methods and set properties very quickly (after an initial setup cost), in case you need to call/set/get the same thing many times, but I have never tried this. @Roberto-Gentili would know the answer to this.

**Comment by Roberto-Gentili** [comment]
> By the way, is there any plan to support other architecture or improve the performance?
> 
> I tested the property access performance with jmh on jdk17-hotspot before, jvm-driver or narcissus is too slow.
> 
> ![image](https://user-images.githubusercontent.com/1670721/172523829-36d59ba7-2b50-4c7c-b1dd-f03202d94676.png)

If you need performance consider to try the [Burningwave Core Reflection components](https://github.com/burningwave/core#handling-privates-and-all-other-members-of-an-object): they uses to cache all members for faster access. The DefaultDriver uses only Java code so it should work on all architecture

**Comment by Roberto-Gentili** [comment]
> OK, it works fine now. Thanks.

Sorry, I accidentally deleted your response with performance data: possibly repost it in your next response.

If you need performance consider to try the [**Burningwave Core Reflection components**](https://github.com/burningwave/core#handling-privates-and-all-other-members-of-an-object): they uses to cache all members (fields, constructors, methods and method handles) for faster access; in this case I also suggest setting the `jvm.driver.init` configuration property to true to ensure that the JVM driver is fully initialized when Burningwave Core starts. The DefaultDriver uses only Java code so it should work on all architecture

**Comment by Roberto-Gentili** [comment]
> OK, it works fine now. Thanks.

Sorry, I accidentally deleted your response with performance data: possibly repost it in your next answer.

If you need performance consider to try the [**Burningwave Core Reflection components**](https://github.com/burningwave/core#handling-privates-and-all-other-members-of-an-object): they uses to cache all members (fields, constructors, methods and method handles) for faster access; in this case I also suggest setting the `jvm.driver.init` configuration property to true to ensure that the JVM driver is fully initialized when Burningwave Core starts. The DefaultDriver uses only Java code so it should work on all architecture

**Comment by Roberto-Gentili** [comment]
> OK, it works fine now. Thanks.


Sorry, I accidentally deleted your response with performance data: possibly repost it in your next answer.

If you need performance consider to try the [**Burningwave Core Reflection components**](https://github.com/burningwave/core#handling-privates-and-all-other-members-of-an-object): they uses to cache all members (fields, constructors, methods and method handles) for faster access; in this case I also suggest setting the `jvm.driver.init` configuration property to true to ensure that the JVM driver is fully initialized when Burningwave Core starts. The DefaultDriver uses only Java code so it should work on all architecture.

Consider also [to export the packages of the modules at runtime](https://jim-jerald-burton.medium.com/exporting-all-modules-to-all-modules-at-runtime-on-java-9-and-later-3517eb479701) through Burningwave Core: in this case you can use the Reflection like before the introduction of the strong incapsulation.

**Comment by Roberto-Gentili** [comment]
> OK, it works fine now. Thanks.

Sorry, I accidentally deleted your response with performance data: possibly repost it in your next answer.

If you need performance consider to try the [**Burningwave Core Reflection components**](https://github.com/burningwave/core#handling-privates-and-all-other-members-of-an-object): they uses to cache all members (fields, constructors, methods and method handles) for faster access; in this case I also suggest setting the `jvm.driver.init` configuration property to true to ensure that the JVM driver is fully initialized when Burningwave Core starts. The DefaultDriver uses only Java code so it should work on all architecture.

Consider also [to export the packages of the modules at runtime](https://jim-jerald-burton.medium.com/exporting-all-modules-to-all-modules-at-runtime-on-java-9-and-later-3517eb479701) through Burningwave Core: in this case you can use the Reflection like before the introduction of the modules.

**Comment by JaynLau** [comment]
The dependent libraries LIBGCC_S_SEH-1.DLL and LIBSTDC++-6.DLL of NativeExecutor-x64.dll on windows (same on 32 bits system) are absent by default. Could you consider compiling them into one dll file?

![image](https://user-images.githubusercontent.com/1670721/172570121-b162c109-bdf5-4f8f-8800-7d2a2326f79f.png)

**Comment by JaynLau** [comment]
Burningwave crashed during initialization.

**Comment by Roberto-Gentili** [comment]
> Burningwave crashed during initialization.

Do you suggest doing a static link to them or what else? Are you using the NativeDriver?

**Comment by Roberto-Gentili** [comment]
> > The dependent libraries LIBGCC_S_SEH-1.DLL and LIBSTDC++-6.DLL of NativeExecutor-x64.dll on windows (same on 32 bits system) are absent by default. Could you consider compiling them into one dll file?
> > ![image](https://user-images.githubusercontent.com/1670721/172570121-b162c109-bdf5-4f8f-8800-7d2a2326f79f.png)
> 
> Does this cause some malfunction in any situation? If yes is there a way to merge DLLs with g++?



> The dependent libraries LIBGCC_S_SEH-1.DLL and LIBSTDC++-6.DLL of NativeExecutor-x64.dll on windows (same on 32 bits system) are absent by default. Could you consider compiling them into one dll file?
> 
> ![image](https://user-images.githubusercontent.com/1670721/172570121-b162c109-bdf5-4f8f-8800-7d2a2326f79f.png)
> 
> I got a link error.
> 
> ![image](https://user-images.githubusercontent.com/1670721/172573817-7141e5f9-20fc-4cd9-8c2b-5c459f0393f6.png)

I will try to add the `-static-libgcc` flag during linking: could you open an issue on [Burningwave JVM Driver Project](https://github.com/burningwave/jvm-driver)

**Comment by JaynLau** [comment]
A simplify way is to include all dlls in the jar of burningwave jvm-driver and extract all dependent dlls into the same directory before call LoadLibrary(). Because the user dosen't know which version of mingw-gcc that you use to compile the NativeExecutor.

**Comment by Roberto-Gentili** [comment]
> A simplify way is to include all dlls in the jar of burningwave jvm-driver and extract all dependent dlls into the same directory before call LoadLibrary(). Because the user dosen't know which version of mingw-gcc that you use to compile the NativeExecutor.

Ok, it's a good solution: could you try this by including the DLLs in the jar and tell me if it works?

**Comment by JaynLau** [comment]
[Dependent libraries are absent on windows](https://github.com/burningwave/jvm-driver/issues/3#issue-1264423993)
